export const LOGIN='LOGIN';
export const LOGIN_INPUT_INIT='LOGIN_INPUT_INIT';
export const LOGIN_ACCOUNT_CHECK='LOGIN_ACCOUNT_CHECK';
export const LOGIN_PASSWORD_CHECK='LOGIN_PASSWORD_CHECK';
export const LOGIN_ACCOUNT_INPUT='LOGIN_ACCOUNT_INPUT';
export const LOGIN_PASSWORD_INPUT='LOGIN_PASSWORD_INPUT';
export const LOGIN_FAILED='LOGIN_FAILED';
export const LOGIN_EXIT='LOGIN_EXIT';

export const PANEL_EXIT='PANEL_EXIT';

export const LOAD_MENU='LOAD_MENU';
export const OPEN_DETAILS='OPEN_DETAILS';
export const ACTIVE_NODE='ACTIVE_NODE';

export const R_OPEN_NODE='R_OPEN_NODE';
export const R_ACTIVE_NODE='R_ACTIVE_NODE';
export const R_CLOSE_NAV='R_CLOSE_NAV';